[FEAT] 공지사항 글 목록 #6
Team-UMC/UMC-Web pull request #11
Opened 2024-01-07 15:35 UTC by chaserChoi

### 🚩 관련 이슈
[FEAT] 공지사항 글 목록 화면 구현

### 📌 반영 브랜치
feat/#6/noticelist -> develop

### 📋 내용
- [ ] ex) Header 구현
- [ ] ex) 왼쪽 : 햄버거 메뉴, 홈, 게시판, 히스토리, 사진첩, UMC 네트워킹
- [ ] ex) 오른쪽 : 설정, 알림, 친구 아이콘

### 🖼️ 사진
- 로그인 전
(사진 첨부)

### 유의 사항
- [ ] ex) 헤더 작아질 때, 사진 바꿔야 함.
- [ ] ex) 스타일 변경 많이 필요함.

2024-01-08 10:48 UTC, JJHyeok13 requested changes
현재 Figma에 수정된 고정핀 이미지가 올라와있으니 수정해주세요 :)

2024-01-08 11:13 UTC, JJHyeok13 requested changes
현재 CSS로 스타일을 적용하고 있는데, styled-components 사용하는 방식으로 수정해주세요 😃

2024-01-11 05:35 UTC, JJHyeok13 approved these changes
접기/펼치기 기능 구현은 이후에 진행하는 것으로 하겠습니다!
LGTM :)

2024-01-11 05:36 UTC, mindidii approved these changes
LGTM

2024-01-11 05:37 UTC, Lio-LWY approved these changes
LGTM

2024-01-11 05:38 UTC, merged